on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lintAndFormatCheck:
    name: Run ESlint and prettier
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run prettier
        run: npm run format-check
